//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G3Pharmaceuticals.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Candidate
    {
        public int CandidateID { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string EducationDetails { get; set; }
        public string CV { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<System.DateTime> InterviewDate { get; set; }
        public string InterviewNote { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
    
        public virtual Staff Staff { get; set; }

        public HttpPostedFileBase cvUpload { get; set; }
    }
}
