//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G3Pharmaceuticals.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Manufacturer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Manufacturer()
        {
            this.Products = new HashSet<Product>();
        }
        [Display(Name = "Manufacturer ID")]
        [Required(ErrorMessage = "Please Enter Manufacturer ID")]
        [Remote("IsIDNameExist", "Manufacturer", ErrorMessage = "Manufacturer ID already exist")]
        public string manufacturerID { get; set; }
        [Display(Name = "Manufacturer Name")]
        [Required(ErrorMessage = "Please Enter Manufacturer Name")]
        public string manufacturerName { get; set; }
        [Display(Name = "Nation")]
        public string nation { get; set; }
    
        public virtual Nation Nation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
