//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G3Pharmaceuticals.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.Candidates = new HashSet<Candidate>();
            this.Orderproes = new HashSet<Orderpro>();
        }
        [Display(Name = "Staff ID")]
        public int StaffID { get; set; }
        [Display(Name = "Staff Name")]
        [Required(ErrorMessage = "Please Enter Staff Name")]
        public string StaffName { get; set; }
        public string TaxCode { get; set; }
        [Required(ErrorMessage = "Please Enter Phone")]
        [RegularExpression(@"(84|0[1|2|3|4|5|6|7|8|9])+([0-9]{8,9})\b", ErrorMessage = "Please enter valid Phone")]
        public string Phone { get; set; }
        [Required(ErrorMessage = "Please Enter Address")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Please Enter Email")]
        [RegularExpression(@"^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$", ErrorMessage = "Please enter valid Email")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please Enter Username")]
        [Remote("IsUserNameExist", "Staff", ErrorMessage = "Username already exist")]
        public string Username { get; set; }
        [Required(ErrorMessage = "Please Enter PassWord")]
        [StringLength(300, MinimumLength = 7, ErrorMessage = "Password length must be atleast 8 characters")]
        public string Password { get; set; }
        public string Images { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Candidate> Candidates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orderpro> Orderproes { get; set; }
    }
}
